"""initial simulation schema

Revision ID: 0001
Revises:
Create Date: 2026-09-14

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "simulations",
        sa.Column("run_id", sa.String(50), nullable=False),
        sa.Column(
            "ingested_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("t", sa.Double(), nullable=False),
        sa.Column("throttle", sa.REAL()),
        sa.Column("alt_m", sa.REAL()),
        sa.Column("ambient_c", sa.REAL()),
        sa.Column("airspeed_ms", sa.REAL()),
        sa.Column("cool_index", sa.REAL()),
        sa.Column("rpm", sa.REAL()),
        sa.Column("map_kpa", sa.REAL()),
        sa.Column("torque_nm", sa.REAL()),
        sa.Column("cht_c", sa.REAL()),
        sa.Column("egt_c", sa.REAL()),
        sa.Column("oil_c", sa.REAL()),
        sa.Column("cht_c_1", sa.REAL()),
        sa.Column("cht_c_2", sa.REAL()),
        sa.Column("cht_c_3", sa.REAL()),
        sa.Column("cht_c_4", sa.REAL()),
        sa.Column("egt_c_1", sa.REAL()),
        sa.Column("egt_c_2", sa.REAL()),
        sa.Column("egt_c_3", sa.REAL()),
        sa.Column("egt_c_4", sa.REAL()),
        sa.Column("air_gps", sa.REAL()),
        sa.Column("fuel_kgph", sa.REAL()),
        sa.Column("fuel_press_kpa", sa.REAL()),
        sa.Column("lambda_1", sa.REAL()),
        sa.Column("lambda_2", sa.REAL()),
        sa.Column("lambda_3", sa.REAL()),
        sa.Column("lambda_4", sa.REAL()),
        sa.Column("oil_press_kpa", sa.REAL()),
        sa.Column("bus_v", sa.REAL()),
        sa.Column("alt_a", sa.REAL()),
        sa.Column("alt_field_a", sa.REAL()),
        sa.Column("batt_soc", sa.REAL()),
    )

    # Timescale-specific: never autogenerated, always explicit.
    # Partitioned on ingested_at (monotonic wall-clock), NOT on sim `time`
    # (which resets per run) — see earlier chunk-partitioning fix.
    op.execute(
        """
        SELECT create_hypertable(
            'simulations',
            'ingested_at',
            chunk_time_interval => INTERVAL '1 day',
            if_not_exists => TRUE
        );
        """
    )

    # Serves the actual /simulations query pattern:
    # WHERE run_id = X AND time BETWEEN a AND b
    op.create_index(
        "ix_simulations_run_time", "simulations", ["run_id", "t"]
    )


def downgrade() -> None:
    # DROP TABLE correctly tears down a hypertable too — no separate
    # Timescale-specific teardown call needed.
    op.drop_index("ix_simulations_run_time", table_name="simulations")